### PR TITLE
pillow 8 exception is different

### PR DESCRIPTION
**Pull request by jensens**
see https://github.com/plone/buildout.coredev/pull/687

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
Unrelated failing robot test :(

**Review by mauritsvanrees — APPROVED** [review]
I confirm this fixes the failure with Pillow 8.

**Pull request merged**
