### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
@mauritsvanrees the test failures seem to be somewhat related to the `latin-1` encoding, or at least is about encoding as well.

Any idea? 🤔 🍀

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees the test failures seem to be somewhat related to the `latin-1` encoding, or at least is about encoding as well.
> 
> Any idea? 🤔 🍀

See my initial commit in PR #60 that was merged and released:

> This PR fixes tests when run with Zope master, once https://github.com/zopefoundation/Zope/pull/1101 is merged.
> The tests would fail with current Zope 5.8.

The last is what you see now in the current PR.
Easiest may be to revisit this once there is a Zope release, and probably also a Plone release.

**Comment by gforcada** [comment]
I change the PR to be a draft one, and let's hope we remember at some point to get it merged 😄

**Comment by gforcada** [comment]
I removed the workflow and the pre-commit integration, otherwise any PR will fail

**Comment by jensens** [comment]
As far as I understand this ready now, right?

**Comment by gforcada** [comment]
Yes, now it should be ready.

I applied the newest version of `plone/meta` just to be sure all is good, let's see what CI / Jenkins say 🍀

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
@jensens @mauritsvanrees this one is ready but merging is blocked by requiring a review, could you have a look? 👼🏾 😄

**Review by mauritsvanrees — APPROVED** [review]
LGTM thanks

**Pull request merged**
