### PR TITLE
range support

### PR DESCRIPTION
**Pull request by mamico**
requires https://github.com/plone/plone.namedfile/pull/86

### CODE REVIEW

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Jenkins [5.1 fails](https://jenkins.plone.org/job/pull-request-5.1/312/testReport/), because the `plone.namedfile` version is not compatible with the changes in this PR.
I have created a branch 2.0.x of `plone.formwidget.namedfile`. Coredev 5.1 now uses this. So we can ignore the 5.1 failure.

Two of the three 5.2 jobs pass, and the failing one is in two unrelated robot tests, likely due to too many parallel jobs being run.
I will merge.

**Pull request merged**
