### PR TITLE
Use plone.app.testing.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
For an upcoming change (for issue #21) we need a fuller test setup, where for example the `@@images` view can be found. So I propose we use plone.app.testing with the PloneSandboxLayer so we have a full Plone Site in the tests. It makes the tests slower, but makes it faster for developers to add more tests without needing to do much mocking.

### CODE REVIEW

**Comment by gforcada** [comment]
Accuracy is always better than speed.

**Comment by mauritsvanrees** [comment]
I have just released 1.0.15 before this change, fine for use on Plone 4.3 and higher.
As for compatibility of this pull request: I would say this targets Plone 5.0 and 5.1. I have started Jenkins jobs for this. Should be fine on 4.3 as well, but development should be low there, so I say we skip it there.

**Comment by jensens** [comment]
Is this right?

1. branch away 1.0.x
2. set on coredev 4.3 this branch to 1.0.x 
3. Merge PR

**Comment by mauritsvanrees** [comment]
Yes, that would be good.

**Pull request merged**
