### PR TITLE
Don’t check for hardcoded image size

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]

**Comment by ale-rt** [comment]
The Plone 5.1 job is obsolete and should be ignored. [Master is on version 2.1](https://github.com/plone/plone.formwidget.namedfile/blob/1189d0e0349bb5251a26491b4bd6feb096f84a3c/setup.py), while [Plone 5.1 uses version 2.0.11](https://github.com/plone/buildout.coredev/blob/85b49234100c16b5175652b64bce7b1ee411472f/versions.cfg#L262)

**Pull request merged**
